### ISSUE TITLE
Documentation is offline

### ISSUE THREAD

**Issue by axello** [vasi/osxutils#10]
Hi, it seems your documentation server is offline
[http://sveinbjorn.org/osxutils_docs](http://sveinbjorn.org/osxutils_docs)

```
Error 401
09:03:48, Thursday, April 9, 2020.
Mentat 5.0 says: Access to page 'osxutils_docs' is restricted 
```

**Comment by vasi** [comment]
Sorry, this isn't my server and I can't control it.
